spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:commerce;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

mock:
  enabled: true

logging:
  level:
    com.example.commerce: DEBUG
